Slider widget template
Stackla/stackla-widget-templates pull request #18
Opened 2024-07-18 04:45 UTC by peng-zhou

# Description of change

Slider widget template

# How have you tested your code?

Staging

# Dependencies

No

2024-07-22 03:55 UTC, olivernosto approved these changes

2024-07-22 03:55 UTC, olivernosto requested changes
Hey @peng-zhou - well done so far. A few things we need to clean up. Could you please clean these up and ill review again ? :)

2024-08-09 01:13 UTC, olivernosto approved these changes

2024-08-09 06:11 UTC, manikandan-ravikumar approved these changes

2024-08-11 23:05 UTC, merged